### ISSUE TITLE
How can I get api_key and api_secret in /config/twilio.php？

### ISSUE THREAD

**Issue by willhunger** [Guley/Twilio-Sms-Codeigniter#1]
I just can get Auth Token and Account Sid in Twilio.
How should I fill these field?

**Comment by Guley** [comment]
Follow these steps:
1.Login here https://www.twilio.com/login with your Twilio login details.
2. go to https://www.twilio.com/console/runtime/overview
3.  Click on https://www.twilio.com/console/runtime/api-keys 
4. Generate a master key for your Twilio account and keep the API key and secret safe.
5. On https://www.twilio.com/console there is a SID KEY auto-generated by Twilio.
